version: '3.8'

services:
  monitor:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:8080"
    container_name: monitor-module-app
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # 添加privileged模式以确保足够权限
    privileged: true
    group_add:
       - 118  # 对应宿主机 docker 组 GID